config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :drivers
  resources :passengers
  resources :trips
  resources :buses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/buses_controller.rb
# app/controllers/buses_controller.rb

class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]

  # GET /buses or /buses.json
  def index
    @buses = Bus.all
  end

  # GET /buses/1 or /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses or /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to bus_url(@bus), notice: "Bus was successfully created." }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1 or /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to bus_url(@bus), notice: "Bus was successfully updated." }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1 or /buses/1.json
  def destroy
    @bus.destroy

    respond_to do |format|
      format.html { redirect_to buses_url, notice: "Bus was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bus_params
      params.require(:bus).permit(:bus_number, :plate_number, :other_attributes, :image)
    end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_bus.html.erb
<div id="<%= dom_id bus %>">
  <p>
    <strong>Bus number:</strong>
    <%= bus.bus_number %>
  </p>

  <p>
    <strong>Plate number:</strong>
    <%= bus.plate_number %>
  </p>

</div>

app/views/buses/_form.html.erb
<%= form_with(model: bus) do |form| %>
  <% if bus.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
        <% bus.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :bus_number, style: "display: block" %>
    <%= form.text_field :bus_number %>
  </div>

  <div>
    <%= form.label :plate_number, style: "display: block" %>
    <%= form.text_field :plate_number %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing bus</h1>

<%= render "form", bus: @bus %>

<br>

<div>
  <%= link_to "Show this bus", @bus %> |
  <%= link_to "Back to buses", buses_path %>
</div>

app/views/buses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Buses</h1>



<table>
  <thead>
    <tr>
      <th>Bus Number</th>
      <th>Plate Number</th>
      <th>Assigned Drivers</th>
      <th>Trips Count</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @buses.each do |bus| %>
      <tr>
        <td><%= bus.bus_number %></td>
        <td><%= bus.plate_number %></td>
        <td>
          <% bus.drivers.each do |driver| %>
            <%= driver.name %><br>
          <% end %>
        </td>
        <td><%= bus.trips.count %></td>
        <td>
          <%= link_to "Show", bus %>
          <%= link_to "Edit", edit_bus_path(bus) %>
          <%= button_to "Destroy", bus, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Bus", new_bus_path, class: "new-bus-button" %>

app/views/buses/new.html.erb
<h1>New bus</h1>

<%= render "form", bus: @bus %>

<br>

<div>
  <%= link_to "Back to buses", buses_path %>
</div>

app/views/buses/show.html.erb
<% if notice %>
  <p style="color: green"><%= notice %></p>
<% end %>

<p></p>

<h2>Bus Information</h2>

<div id="<%= dom_id @bus %>">
  <p>
    <strong>Bus number:</strong>
    <%= @bus.bus_number %>
  </p>

  <p>
    <strong>Plate number:</strong>
    <%= @bus.plate_number %>
  </p>

  <% if @bus.image.attached? %>
  <p>
  
    <%= image_tag rails_blob_path(@bus.image) %>
  </p>
<% end %>

<h2>Trips</h2>
<table>
  <thead>
    <tr>
      <th>Schedule</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Number of Passengers</th>
      <th>Unit Fare</th>
      <th>Total Fare</th>
    </tr>
  </thead>
  <tbody>
    <% @bus.trips.each do |trip| %>
      <tr>
        <td><%= trip.schedule.strftime("%m/%d/%Y, %I:%M %p") %></td>
        <td><%= trip.origin %></td>
        <td><%= trip.destination %></td>
        <td><%= trip.number_of_passengers %></td>
        <td><%= number_to_currency(trip.unit_fare, unit: '') %></td>
        <td><%= number_to_currency(trip.total_fare, unit: '') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  
<h2>Driver(s)</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact Number</th>
    </tr>
  </thead>
  <tbody>
    <% @bus.drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.contact_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Edit this bus", edit_bus_path(@bus) %> |
  <%= link_to "Back to buses", buses_path %> |
  <%= button_to "Destroy this bus", @bus, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>